# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\xcf\x01\n\x07\x43ommand\x12/\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x19.raft.Command.CommandType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x12\n\x05value\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x16\n\told_value\x18\x04 \x01(\tH\x01\x88\x01\x01\"B\n\x0b\x43ommandType\x12\n\n\x06\x43reate\x10\x00\x12\n\n\x06Update\x10\x01\x12\n\n\x06\x44\x65lete\x10\x02\x12\x0f\n\x0b\x43ompareSwap\x10\x03\x42\x08\n\x06_valueB\x0c\n\n_old_value\"G\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x1e\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\r.raft.Command\".\n\x0eWriteAheadLogs\x12\x1c\n\x04logs\x18\x01 \x03(\x0b\x32\x0e.raft.LogEntry\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x04\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x9e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\x04\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xa1\x01\n\rRaftConsensus\x12\x44\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\"\x00\x12J\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=21
  _globals['_COMMAND']._serialized_end=228
  _globals['_COMMAND_COMMANDTYPE']._serialized_start=138
  _globals['_COMMAND_COMMANDTYPE']._serialized_end=204
  _globals['_LOGENTRY']._serialized_start=230
  _globals['_LOGENTRY']._serialized_end=301
  _globals['_WRITEAHEADLOGS']._serialized_start=303
  _globals['_WRITEAHEADLOGS']._serialized_end=349
  _globals['_REQUESTVOTEREQUEST']._serialized_start=351
  _globals['_REQUESTVOTEREQUEST']._serialized_end=454
  _globals['_REQUESTVOTERESPONSE']._serialized_start=456
  _globals['_REQUESTVOTERESPONSE']._serialized_end=513
  _globals['_APPENDENTRIESREQUEST']._serialized_start=516
  _globals['_APPENDENTRIESREQUEST']._serialized_end=674
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=676
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=730
  _globals['_RAFTCONSENSUS']._serialized_start=733
  _globals['_RAFTCONSENSUS']._serialized_end=894
# @@protoc_insertion_point(module_scope)
